MONGODB_HOST: mongodb-{{ env }}.userbolla.store # mongodb-dev.daws86s.fun
REDIS_HOST: redis-{{ env }}.userbolla.store
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.userbolla.store
CART_HOST: cart.backend-alb-{{ env }}.userbolla.store
USER_HOST: user.backend-alb-{{ env }}.userbolla.store
RABBITMQ_HOST: rabbitmq-{{ env }}.userbolla.store
MYSQL_HOST: mysql-{{ env }}.userbolla.store
SHIPPING_HOST: shipping.backend-alb-{{ env }}.userbolla.store
PAYMENT_HOST: payment.backend-alb-{{ env }}.userbolla.store